on:
  pull_request:
    paths:
      - '*.swift'
      - .github/workflows/ci.yml
    schedule:
      - cron: '3 3 * * 3'  # 3:03 AM, every Wednesday
jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [^10, ^11, ^12]
        conf: [release, debug]
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/xcodebuild@v1
      with:
        xcode: ${{ matrix.xcode }}
        configuration: ${{ matrix.conf }}
        warnings-as-errors: true
        action: build
